version: "3.9"

networks:
  project_network:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: '${APP_NAME}-server'
    ports:
      - '${SERVER_PORT}:80'
    working_dir: /var/www/html
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5'
    volumes:
      - ./codebase/www:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      db_server:
        condition: service_healthy
    networks:
      - project_network

  db_server:
    image: mariadb:10.5.9
    container_name: '${APP_NAME}-db'
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./docker/db_data:/var/lib/mysql
      - ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - project_network

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${APP_NAME}-phpmyadmin'
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: db_server
    depends_on:
      db_server:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/html
    networks:
      - project_network

  mailhog:
    image: mailhog/mailhog
    container_name: '${APP_NAME}-mailhog'
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - ${MAILHOG_SMTP_PORT}:1025 # smtp server
      - ${MAILHOG_UI_PORT}:8025 # web ui

volumes:
  db_data:
  db_admin_data: